name: untitled
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  logger: ^1.1.0
  cached_network_image: ^3.2.3
  firebase_core: ^2.4.1
  google_sign_in: ^5.4.3
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

